- direction: GZ_TO_ROS
  gz_topic_name: /clock
  gz_type_name: gz.msgs.Clock
  ros_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
- direction: ROS_TO_GZ
  gz_topic_name: /cmd_vel
  gz_type_name: gz.msgs.Twist
  ros_topic_name: /cmd_vel
  ros_type_name: geometry_msgs/msg/Twist
- direction: GZ_TO_ROS
  gz_topic_name: /odom
  gz_type_name: gz.msgs.Odometry
  ros_topic_name: /odom
  ros_type_name: nav_msgs/msg/Odometry
- direction: GZ_TO_ROS
  gz_topic_name: /tf
  gz_type_name: gz.msgs.Pose_V
  ros_topic_name: /tf
  ros_type_name: tf2_msgs/msg/TFMessage
- direction: GZ_TO_ROS
  gz_topic_name: /lidar
  gz_type_name: gz.msgs.LaserScan
  ros_topic_name: /scan
  ros_type_name: sensor_msgs/msg/LaserScan
- direction: GZ_TO_ROS
  gz_topic_name: /rgbd_camera/image
  gz_type_name: gz.msgs.Image
  ros_topic_name: /camera/color/image_raw
  ros_type_name: sensor_msgs/msg/Image
- direction: GZ_TO_ROS
  gz_topic_name: /rgbd_camera/depth_image
  gz_type_name: gz.msgs.Image
  ros_topic_name: /camera/depth/image_rect_raw
  ros_type_name: sensor_msgs/msg/Image
- direction: GZ_TO_ROS
  gz_topic_name: /rgbd_camera/points
  gz_type_name: gz.msgs.PointCloudPacked
  ros_topic_name: /camera/depth/color/points
  ros_type_name: sensor_msgs/msg/PointCloud2
- direction: GZ_TO_ROS
  gz_topic_name: /rgbd_camera/camera_info
  gz_type_name: gz.msgs.CameraInfo
  ros_topic_name: /camera/camera_info
  ros_type_name: sensor_msgs/msg/CameraInfo
- direction: GZ_TO_ROS
  gz_topic_name: /camera_imu
  gz_type_name: gz.msgs.IMU
  ros_topic_name: /camera/imu
  ros_type_name: sensor_msgs/msg/Imu
- direction: GZ_TO_ROS
  gz_topic_name: /imu/data
  gz_type_name: gz.msgs.IMU
  ros_topic_name: /imu/data
  ros_type_name: sensor_msgs/msg/Imu
- direction: GZ_TO_ROS
  gz_topic_name: /world/outdoor_terrain/pose/info
  gz_type_name: gz.msgs.Pose_V
  ros_topic_name: /gz_poses
  ros_type_name: tf2_msgs/msg/TFMessage
- direction: GZ_TO_ROS
  gz_topic_name: /world/outdoor_terrain/dynamic_pose/info
  gz_type_name: gz.msgs.Pose_V
  ros_topic_name: /ground_truth/dynamic_poses
  ros_type_name: tf2_msgs/msg/TFMessage
